export const POSTS_LOADING='POSTS_LOADING';
export const POSTS_FAILED='POSTS_FAILED';
export const ADD_POSTS='ADD_POSTS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LIKES_REQUEST='LIKES_REQUEST';
export const ADD_LIKES='ADD_LIKES';
export const LIKES_FAILED='LIKES_FAILED';
export const ADD_LIKE='ADD_LIKE';

export const UNLIKES_REQUEST='UNLIKES_REQUEST';
export const UNLIKES_SUCCESS='UNLIKES_SUCCESS';
export const UNLIKES_FAILED='UNLIKES_FAILED';


export const LIKE_REQUEST='LIKE_REQUEST';
export const LIKE_SUCCESS='LIKE_SUCCESS';
export const LIKE_FAILED='LIKE_FAILED';


export const COMMENT_REQUEST='COMMENT_REQUEST';
export const COMMENT_SUCCESS='COMMENT_SUCCESS'
export const COMMENT_FAILED='COMMENT_FAILED';

export const UPLOADIMG_REQUEST='UPLOADIMG_REQUEST';
export const UPLOADIMG_SUCCESS='UPLOADIMG_SUCCESS';
export const UPLOADIMG_FAILED='UPLOADIMG_FAILED';

export const UPLOAD_REQUEST='UPLOAD_REQUEST';
export const UPLOAD_SUCCESS='UPLOAD_SUCCESS';
export const UPLOAD_FAILED='UPLOAD_FAILED';


export const PROFILE_REQUEST='PROFILE_REQUEST';
export const PROFILE_FAILED='PROFILE_FAILED';
export const ADD_PROFILE='ADD_PROFILE';

export const USER_REQUEST='USER_REQUEST';
export const USER_SUCCESS='USER_SUCCESS';
export const USER_FAILED='USER_FAILED';

export const USERPIC_REQUEST='USERPIC_REQUEST';
export const USERPIC_SUCCESS='USERPIC_SUCCESS';
export const USERPIC_FAILED='USERPIC_FAILED';

export const OUSER_REQUEST='OUSER_REQUEST';
export const OUSER_SUCCESS='OUSER_SUCCESS';
export const OUSER_FAILED='OUSER_FAILED';

export const OUSER_FOLLOW_REQUEST='OUSER_FOLLOW_REQUEST';
export const OUSER_FOLLOW_SUCCESS='OUSER_FOLLOW_SUCCESS';
export const OUSER_FOLLOW_FAILED='OUSER_FOLLOW_FAILED';

export const OUSER_UNFOLLOW_REQUEST='OUSER_UNFOLLOW_REQUEST';
export const OUSER_UNFOLLOW_SUCCESS='OUSER_UNFOLLOW_SUCCESS';
export const OUSER_UNFOLLOW_FAILED='OUSER_UNFOLLOW_FAILED';


export const FOLLOWING_POSTS_LOADING='FOLLOWING_POSTS_LOADING';
export const FOLLOWING_POSTS_FAILED='FOLLOWING_POSTS_FAILED';
export const FOLLOWING_POSTS_SUCCESS='FOLLOWING_POSTS_SUCCESS';

export const DELETE_REQUEST='DELETE_REQUEST';
export const DELETE_SUCCESS='DELETE_SUCCESS'
export const DELETE_FAILED='DELETE_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const ADD_COMMENT='ADD_COMMENT';

export const ADD_SEARCH_USERS='ADD_SEARCH_USERS';
export const SEARCH_LOADING='SEARCH_LOADING';
export const SEARCH_FAILED='SEARCH_FAILED';